#!/bin/bash
##########################################################################
## Jonah Duckles (c) 2014 - jduckles@ou.edu
## Wrapper to run rsync with custom SSH ProxyCommand's to pierce firewall 
##
##########################################################################

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
SSH_CONFIG=ssh_config
DATADIR=/data/iCarbon/
SENSOR=LI-7550

_licor() {
    SITE=$1
    SITETAG=$2
    EXCLUDE="--exclude .Spotlight-V100"
    mkdir -p ${DATADIR}/${SITETAG}/${SENSOR}
    rsync ${EXCLUDE} -avz -e "ssh -v -F ${SSH_CONFIG}" ${SITE} ${DATADIR}/${SITETAG}/${SENSOR}
}

_phenocam {
    SITE=$1
    OUTFILE=$2
    PORT=$3
    wget localhost:${PORT} -O ${OUTFILE}
}

igos-east-licor() {
    SITE=licor-igos-east:data
    SITETAG=iGOS_East
    _licor ${SITE} ${SITETAG}
}

igos-west-licor() {
    SITE=licor-igos-west:data
    SITETAG=iGOS_West
    _licor ${SITE} ${SITETAG}
}

icos-east-licor() {
    SITE=licor-icos-east:data
    SITETAG=iCOS_East
    _licor ${SITE} ${SITETAG}
}

igos-east-phenocam() {
    SITE=igos-east-phenocam

}

main() {
    $1
}

main $1
